// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Skyrim;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class SailorMoonClub
    {
        public static class Activator
        {
            private static FormLink<IActivatorGetter> Construct(uint id) => new FormLink<IActivatorGetter>(ModKey.MakeFormKey(id));
            public static FormLink<IActivatorGetter> MoonPearlSconce => Construct(0x9220);
            public static FormLink<IActivatorGetter> SMC_MoonForgeController => Construct(0xb8f0);
            public static FormLink<IActivatorGetter> SMC_LCOController => Construct(0x70aa0);
            public static FormLink<IActivatorGetter> SMC_LCOTrigger => Construct(0x86f99);
        }
    }
}
