// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class SailorMoonClub
    {
        public static class Activator
        {
            private static FormLink<IActivatorGetter> Construct(uint id) => new FormLink<IActivatorGetter>(ModKey.MakeFormKey(id));
            public static FormLink<IActivatorGetter> MoonPearlSconce => Construct(0x892);
            public static FormLink<IActivatorGetter> SMC_MoonForgeController => Construct(0x8a2);
            public static FormLink<IActivatorGetter> SMC_LCOController => Construct(0xc30);
            public static FormLink<IActivatorGetter> SMC_LCOTrigger => Construct(0xcba);
        }
    }
}
