// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class SailorMoonClub
    {
        public static class FormList
        {
            private static FormLink<IFormListGetter> Construct(uint id) => new FormLink<IFormListGetter>(ModKey.MakeFormKey(id));
            public static FormLink<IFormListGetter> LunarForge_UnenchantedFLST => Construct(0x888);
            public static FormLink<IFormListGetter> LunarForge_LunarBasicFLST => Construct(0x889);
            public static FormLink<IFormListGetter> LunarForge_AwakenedLunarFLST => Construct(0x88a);
            public static FormLink<IFormListGetter> LunarForge_LunarAbsorbFLST => Construct(0x88b);
            public static FormLink<IFormListGetter> SMC_LeverPackageList => Construct(0xbe4);
        }
    }
}
