// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Skyrim;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class SailorMoonClub
    {
        public static class Global
        {
            private static FormLink<IGlobalGetter> Construct(uint id) => new FormLink<IGlobalGetter>(ModKey.MakeFormKey(id));
            public static FormLink<IGlobalGetter> MoonPhase_New => Construct(0x6586);
            public static FormLink<IGlobalGetter> MoonPhase_Current => Construct(0x6580);
            public static FormLink<IGlobalGetter> MoonPhase_Full => Construct(0x6582);
            public static FormLink<IGlobalGetter> MoonPhase_WaningGibbous => Construct(0x6583);
            public static FormLink<IGlobalGetter> MoonPhase_SecondQuarter => Construct(0x6584);
            public static FormLink<IGlobalGetter> MoonPhase_WaningCrescent => Construct(0x6585);
            public static FormLink<IGlobalGetter> SMC_UpdateRTDelay => Construct(0x6e302);
            public static FormLink<IGlobalGetter> MoonPhase_WaxingCrescent => Construct(0x6587);
            public static FormLink<IGlobalGetter> MoonPhase_FirstQuarter => Construct(0x6588);
            public static FormLink<IGlobalGetter> MoonPhase_WaxingGibbous => Construct(0x6589);
            public static FormLink<IGlobalGetter> Hour_Moonrise => Construct(0x6aef);
            public static FormLink<IGlobalGetter> Hour_Moonset => Construct(0x6af0);
            public static FormLink<IGlobalGetter> LunarForgeState => Construct(0xc921);
            public static FormLink<IGlobalGetter> SMC_UpdateGTDelay => Construct(0x6e303);
        }
    }
}
