// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class SailorMoonClub
    {
        public static class LeveledItem
        {
            private static FormLink<ILeveledItemGetter> Construct(uint id) => new FormLink<ILeveledItemGetter>(ModKey.MakeFormKey(id));
            public static FormLink<ILeveledItemGetter> LItemSoup => Construct(0x911);
            public static FormLink<ILeveledItemGetter> LunarEnchWeaponSword => Construct(0xa17);
            public static FormLink<ILeveledItemGetter> LunarEnchWeaponWarAxe => Construct(0xa18);
            public static FormLink<ILeveledItemGetter> LunarEnchWeaponAll => Construct(0xa20);
            public static FormLink<ILeveledItemGetter> SMC_ImperialGear => Construct(0xc3e);
            public static FormLink<ILeveledItemGetter> SMC_ImperialSwordLunarEnch20 => Construct(0xc3f);
            public static FormLink<ILeveledItemGetter> SMC_ImperialSwordLunarEnch => Construct(0xc40);
            public static FormLink<ILeveledItemGetter> LunarEnchWeaponMace => Construct(0xa19);
            public static FormLink<ILeveledItemGetter> LunarEnchWeaponGreatsword => Construct(0xa1a);
            public static FormLink<ILeveledItemGetter> LunarEnchWeaponBattleaxe => Construct(0xa1b);
            public static FormLink<ILeveledItemGetter> LunarEnchWeaponWarhammer => Construct(0xa1c);
            public static FormLink<ILeveledItemGetter> LunarEnchWeaponDagger => Construct(0xa1d);
            public static FormLink<ILeveledItemGetter> LunarEnchWeaponBow => Construct(0xa1e);
            public static FormLink<ILeveledItemGetter> LunarEnchWeapon2H => Construct(0xa1f);
            public static FormLink<ILeveledItemGetter> SMC_StormcloakWeaponAny => Construct(0xc47);
            public static FormLink<ILeveledItemGetter> SMC_StormcloakWeaponShield => Construct(0xc48);
            public static FormLink<ILeveledItemGetter> SMC_StormcloakWeapon2H => Construct(0xc49);
            public static FormLink<ILeveledItemGetter> SMC_StormcloakWeapon1H => Construct(0xc4a);
            public static FormLink<ILeveledItemGetter> SMC_StormcloakGear => Construct(0xc46);
            public static FormLink<ILeveledItemGetter> SMC_StormcloakLunarMace => Construct(0xc4b);
            public static FormLink<ILeveledItemGetter> SMC_StormcloakLunarSword => Construct(0xc4c);
            public static FormLink<ILeveledItemGetter> SMC_StormcloakLunarWarAxe => Construct(0xc4d);
            public static FormLink<ILeveledItemGetter> SMC_StormcloakLunarWarhammer => Construct(0xc4e);
            public static FormLink<ILeveledItemGetter> SMC_StormcloakLunarGreatsword => Construct(0xc4f);
            public static FormLink<ILeveledItemGetter> SMC_StormcloakLunarBattleaxe => Construct(0xc50);
        }
    }
}
