// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Skyrim;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class SailorMoonClub
    {
        public static class LeveledItem
        {
            private static FormLink<ILeveledItemGetter> Construct(uint id) => new FormLink<ILeveledItemGetter>(ModKey.MakeFormKey(id));
            public static FormLink<ILeveledItemGetter> LunarEnchWeaponAll => Construct(0x1f969);
            public static FormLink<ILeveledItemGetter> LItemSoup => Construct(0x13ba7);
            public static FormLink<ILeveledItemGetter> LunarEnchWeaponSword => Construct(0x1f960);
            public static FormLink<ILeveledItemGetter> LunarEnchWeaponWarAxe => Construct(0x1f961);
            public static FormLink<ILeveledItemGetter> LunarEnchWeaponMace => Construct(0x1f962);
            public static FormLink<ILeveledItemGetter> LunarEnchWeaponGreatsword => Construct(0x1f963);
            public static FormLink<ILeveledItemGetter> LunarEnchWeaponBattleaxe => Construct(0x1f964);
            public static FormLink<ILeveledItemGetter> LunarEnchWeaponWarhammer => Construct(0x1f965);
            public static FormLink<ILeveledItemGetter> LunarEnchWeaponDagger => Construct(0x1f966);
            public static FormLink<ILeveledItemGetter> LunarEnchWeaponBow => Construct(0x1f967);
            public static FormLink<ILeveledItemGetter> LunarEnchWeapon2H => Construct(0x1f968);
            public static FormLink<ILeveledItemGetter> SMC_StormcloakLunarBattleaxe => Construct(0x7325b);
            public static FormLink<ILeveledItemGetter> SMC_ImperialGear => Construct(0x70aaf);
            public static FormLink<ILeveledItemGetter> SMC_ImperialSwordLunarEnch20 => Construct(0x70ab0);
            public static FormLink<ILeveledItemGetter> SMC_ImperialSwordLunarEnch => Construct(0x70ab1);
            public static FormLink<ILeveledItemGetter> SMC_StormcloakGear => Construct(0x73251);
            public static FormLink<ILeveledItemGetter> SMC_StormcloakWeaponAny => Construct(0x73252);
            public static FormLink<ILeveledItemGetter> SMC_StormcloakWeaponShield => Construct(0x73253);
            public static FormLink<ILeveledItemGetter> SMC_StormcloakWeapon2H => Construct(0x73254);
            public static FormLink<ILeveledItemGetter> SMC_StormcloakWeapon1H => Construct(0x73255);
            public static FormLink<ILeveledItemGetter> SMC_StormcloakLunarMace => Construct(0x73256);
            public static FormLink<ILeveledItemGetter> SMC_StormcloakLunarSword => Construct(0x73257);
            public static FormLink<ILeveledItemGetter> SMC_StormcloakLunarWarAxe => Construct(0x73258);
            public static FormLink<ILeveledItemGetter> SMC_StormcloakLunarWarhammer => Construct(0x73259);
            public static FormLink<ILeveledItemGetter> SMC_StormcloakLunarGreatsword => Construct(0x7325a);
        }
    }
}
