// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Skyrim;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class SailorMoonClub
    {
        public static class MagicEffect
        {
            private static FormLink<IMagicEffectGetter> Construct(uint id) => new FormLink<IMagicEffectGetter>(ModKey.MakeFormKey(id));
            public static FormLink<IMagicEffectGetter> SMC_EnchParanoiaEffect => Construct(0x31882);
            public static FormLink<IMagicEffectGetter> EnchMoonAbsorbHealthFFContact => Construct(0x3318);
            public static FormLink<IMagicEffectGetter> dunSilentMoonsPlusPlusEnchFFContact => Construct(0x6016);
            public static FormLink<IMagicEffectGetter> dunSilentMoonsEnchPlusFFContact => Construct(0x6017);
            public static FormLink<IMagicEffectGetter> TF_StaggerContact => Construct(0x13bb5);
        }
    }
}
