// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class SailorMoonClub
    {
        public static class Message
        {
            private static FormLink<IMessageGetter> Construct(uint id) => new FormLink<IMessageGetter>(ModKey.MakeFormKey(id));
            public static FormLink<IMessageGetter> NoMoonPearl => Construct(0x89a);
            public static FormLink<IMessageGetter> SMC_PlaceSwordMessage => Construct(0x8ab);
            public static FormLink<IMessageGetter> SMC_NoClaim => Construct(0xc2e);
            public static FormLink<IMessageGetter> SMC_ClaimMessage => Construct(0xc2f);
        }
    }
}
