// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class SailorMoonClub
    {
        public static class Npc
        {
            private static FormLink<INpcGetter> Construct(uint id) => new FormLink<INpcGetter>(ModKey.MakeFormKey(id));
            public static FormLink<INpcGetter> SMC_LeverBandit => Construct(0xbe2);
            public static FormLink<INpcGetter> SMC_BanditAlchemist => Construct(0xc17);
            public static FormLink<INpcGetter> SMC_WhiterunHoldGuard => Construct(0xc3d);
            public static FormLink<INpcGetter> SMC_SoldierImperial => Construct(0xc44);
            public static FormLink<INpcGetter> SMC_CagedWolf => Construct(0xbcc);
            public static FormLink<INpcGetter> SMC_SoldierSons => Construct(0xc45);
        }
    }
}
