// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Skyrim;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class SailorMoonClub
    {
        public static class Npc
        {
            private static FormLink<INpcGetter> Construct(uint id) => new FormLink<INpcGetter>(ModKey.MakeFormKey(id));
            public static FormLink<INpcGetter> SMC_LeverBandit => Construct(0x5b104);
            public static FormLink<INpcGetter> SMC_BanditAlchemist => Construct(0x5d188);
            public static FormLink<INpcGetter> SMC_WhiterunHoldGuard => Construct(0x70aae);
            public static FormLink<INpcGetter> SMC_SoldierImperial => Construct(0x7324f);
            public static FormLink<INpcGetter> SMC_SoldierSons => Construct(0x73250);
            public static FormLink<INpcGetter> SMC_CagedWolf => Construct(0x5909a);
        }
    }
}
