// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Skyrim;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class SailorMoonClub
    {
        public static class ObjectEffect
        {
            private static FormLink<IObjectEffectGetter> Construct(uint id) => new FormLink<IObjectEffectGetter>(ModKey.MakeFormKey(id));
            public static FormLink<IObjectEffectGetter> EnchWeaponLunarDamagePlus03 => Construct(0x6aed);
            public static FormLink<IObjectEffectGetter> EnchWeaponLunarDamage04 => Construct(0x6018);
            public static FormLink<IObjectEffectGetter> EnchWeaponLunarDamage05 => Construct(0x6019);
            public static FormLink<IObjectEffectGetter> EnchWeaponLunarDamage06 => Construct(0x601b);
            public static FormLink<IObjectEffectGetter> EnchWeaponLunarDamagePlus01 => Construct(0x657f);
            public static FormLink<IObjectEffectGetter> EnchWeaponLunarDamagePlus02 => Construct(0x6aec);
            public static FormLink<IObjectEffectGetter> SMC_EnchParanoia => Construct(0x31883);
            public static FormLink<IObjectEffectGetter> EnchWeaponLunarDamagePlus04 => Construct(0x6aee);
            public static FormLink<IObjectEffectGetter> EnchWeaponLunarDamagePlus05 => Construct(0x6af1);
            public static FormLink<IObjectEffectGetter> EnchWeaponLunarDamagePlus06 => Construct(0x6af2);
            public static FormLink<IObjectEffectGetter> EnchWeaponLunarAbsorbHealth01 => Construct(0x75b7);
            public static FormLink<IObjectEffectGetter> EnchWeaponLunarAbsorbHealth02 => Construct(0x75b8);
            public static FormLink<IObjectEffectGetter> EnchWeaponLunarAbsorbHealth03 => Construct(0x75ba);
            public static FormLink<IObjectEffectGetter> EnchWeaponLunarAbsorbHealth04 => Construct(0x75bc);
            public static FormLink<IObjectEffectGetter> EnchWeaponLunarAbsorbHealth05 => Construct(0x75be);
            public static FormLink<IObjectEffectGetter> EnchWeaponLunarAbsorbHealth06 => Construct(0x75c0);
            public static FormLink<IObjectEffectGetter> TF_Ench => Construct(0x14118);
        }
    }
}
