// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class SailorMoonClub
    {
        public static class ObjectEffect
        {
            private static FormLink<IObjectEffectGetter> Construct(uint id) => new FormLink<IObjectEffectGetter>(ModKey.MakeFormKey(id));
            public static FormLink<IObjectEffectGetter> TF_Ench => Construct(0x920);
            public static FormLink<IObjectEffectGetter> SMC_EnchParanoia => Construct(0xb3e);
            public static FormLink<IObjectEffectGetter> EnchWeaponLunarDamage04 => Construct(0x86e);
            public static FormLink<IObjectEffectGetter> EnchWeaponLunarDamage05 => Construct(0x86f);
            public static FormLink<IObjectEffectGetter> EnchWeaponLunarDamage06 => Construct(0x870);
            public static FormLink<IObjectEffectGetter> EnchWeaponLunarDamagePlus01 => Construct(0x871);
            public static FormLink<IObjectEffectGetter> EnchWeaponLunarDamagePlus02 => Construct(0x87b);
            public static FormLink<IObjectEffectGetter> EnchWeaponLunarDamagePlus03 => Construct(0x87c);
            public static FormLink<IObjectEffectGetter> EnchWeaponLunarDamagePlus04 => Construct(0x87d);
            public static FormLink<IObjectEffectGetter> EnchWeaponLunarDamagePlus05 => Construct(0x880);
            public static FormLink<IObjectEffectGetter> EnchWeaponLunarDamagePlus06 => Construct(0x881);
            public static FormLink<IObjectEffectGetter> EnchWeaponLunarAbsorbHealth01 => Construct(0x882);
            public static FormLink<IObjectEffectGetter> EnchWeaponLunarAbsorbHealth02 => Construct(0x883);
            public static FormLink<IObjectEffectGetter> EnchWeaponLunarAbsorbHealth03 => Construct(0x884);
            public static FormLink<IObjectEffectGetter> EnchWeaponLunarAbsorbHealth04 => Construct(0x885);
            public static FormLink<IObjectEffectGetter> EnchWeaponLunarAbsorbHealth05 => Construct(0x886);
            public static FormLink<IObjectEffectGetter> EnchWeaponLunarAbsorbHealth06 => Construct(0x887);
        }
    }
}
