// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class SailorMoonClub
    {
        public static class PlacedObject
        {
            private static FormLink<IPlacedObjectGetter> Construct(uint id) => new FormLink<IPlacedObjectGetter>(ModKey.MakeFormKey(id));
            public static FormLink<IPlacedObjectGetter> MoonPearl01 => Construct(0x897);
            public static FormLink<IPlacedObjectGetter> SMC_DefaultBanner => Construct(0xc32);
            public static FormLink<IPlacedObjectGetter> SMC_WhiterunBanner => Construct(0xc33);
            public static FormLink<IPlacedObjectGetter> Sconce01 => Construct(0x88d);
            public static FormLink<IPlacedObjectGetter> Pillar01 => Construct(0x89c);
            public static FormLink<IPlacedObjectGetter> MoonPearl03 => Construct(0x895);
            public static FormLink<IPlacedObjectGetter> SMC_ImperialBanner => Construct(0xc34);
            public static FormLink<IPlacedObjectGetter> SMC_StormcloakBanner => Construct(0xc35);
            public static FormLink<IPlacedObjectGetter> Pillar04 => Construct(0x89f);
            public static FormLink<IPlacedObjectGetter> SMC_ImperialMarker => Construct(0xc38);
            public static FormLink<IPlacedObjectGetter> Pillar02 => Construct(0x89d);
            public static FormLink<IPlacedObjectGetter> SMC_ControllerSwordBox => Construct(0xbb4);
            public static FormLink<IPlacedObjectGetter> Pillar_ForgeController => Construct(0x8a8);
            public static FormLink<IPlacedObjectGetter> Pillar03 => Construct(0x89e);
            public static FormLink<IPlacedObjectGetter> MoonPearl02 => Construct(0x896);
            public static FormLink<IPlacedObjectGetter> Sconce02 => Construct(0x88e);
            public static FormLink<IPlacedObjectGetter> MoonPearl04 => Construct(0x894);
            public static FormLink<IPlacedObjectGetter> SMC_BanditMarker => Construct(0xc36);
            public static FormLink<IPlacedObjectGetter> MoonPearl05 => Construct(0x893);
            public static FormLink<IPlacedObjectGetter> Sconce04 => Construct(0x890);
            public static FormLink<IPlacedObjectGetter> Pillar05 => Construct(0x8a0);
            public static FormLink<IPlacedObjectGetter> SMC_WhiterunMarker => Construct(0xc37);
            public static FormLink<IPlacedObjectGetter> Sconce05 => Construct(0x891);
            public static FormLink<IPlacedObjectGetter> SMC_StormcloakMarker => Construct(0xc39);
            public static FormLink<IPlacedObjectGetter> Sconce03 => Construct(0x88f);
        }
    }
}
