// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Skyrim;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class SailorMoonClub
    {
        public static class PlacedObject
        {
            private static FormLink<IPlacedObjectGetter> Construct(uint id) => new FormLink<IPlacedObjectGetter>(ModKey.MakeFormKey(id));
            public static FormLink<IPlacedObjectGetter> SMC_BanditMarker => Construct(0x70aa7);
            public static FormLink<IPlacedObjectGetter> SMC_ImperialBanner => Construct(0x70aa5);
            public static FormLink<IPlacedObjectGetter> SMC_DefaultBanner => Construct(0x70aa3);
            public static FormLink<IPlacedObjectGetter> MoonPearl02 => Construct(0x978c);
            public static FormLink<IPlacedObjectGetter> SMC_ControllerSwordBox => Construct(0x3eb50);
            public static FormLink<IPlacedObjectGetter> Pillar_ForgeController => Construct(0xb8f6);
            public static FormLink<IPlacedObjectGetter> Pillar04 => Construct(0xb38b);
            public static FormLink<IPlacedObjectGetter> Pillar03 => Construct(0xb38a);
            public static FormLink<IPlacedObjectGetter> MoonPearl01 => Construct(0x978d);
            public static FormLink<IPlacedObjectGetter> MoonPearl03 => Construct(0x978b);
            public static FormLink<IPlacedObjectGetter> MoonPearl04 => Construct(0x978a);
            public static FormLink<IPlacedObjectGetter> MoonPearl05 => Construct(0x9789);
            public static FormLink<IPlacedObjectGetter> Sconce04 => Construct(0x8cbc);
            public static FormLink<IPlacedObjectGetter> Sconce03 => Construct(0x8cbb);
            public static FormLink<IPlacedObjectGetter> Sconce02 => Construct(0x8cba);
            public static FormLink<IPlacedObjectGetter> SMC_WhiterunMarker => Construct(0x70aa8);
            public static FormLink<IPlacedObjectGetter> Pillar02 => Construct(0xb388);
            public static FormLink<IPlacedObjectGetter> SMC_StormcloakMarker => Construct(0x70aaa);
            public static FormLink<IPlacedObjectGetter> Sconce05 => Construct(0x8cbd);
            public static FormLink<IPlacedObjectGetter> Pillar05 => Construct(0xb38c);
            public static FormLink<IPlacedObjectGetter> Sconce01 => Construct(0x8cb9);
            public static FormLink<IPlacedObjectGetter> SMC_WhiterunBanner => Construct(0x70aa4);
            public static FormLink<IPlacedObjectGetter> Pillar01 => Construct(0xb387);
            public static FormLink<IPlacedObjectGetter> SMC_StormcloakBanner => Construct(0x70aa6);
            public static FormLink<IPlacedObjectGetter> SMC_ImperialMarker => Construct(0x70aa9);
        }
    }
}
