// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Skyrim;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class SailorMoonClub
    {
        public static class Static
        {
            private static FormLink<IStaticGetter> Construct(uint id) => new FormLink<IStaticGetter>(ModKey.MakeFormKey(id));
            public static FormLink<IStaticGetter> NorTowerRuinsBase => Construct(0x1362e);
            public static FormLink<IStaticGetter> SMC_MoonPearlStatic => Construct(0x9dfb);
            public static FormLink<IStaticGetter> SMC_PortGateBaseStone => Construct(0xb8f5);
            public static FormLink<IStaticGetter> SMC_SilverSwordStatic => Construct(0xb8f8);
            public static FormLink<IStaticGetter> StockadeSupportedWoodStairs => Construct(0x125e2);
            public static FormLink<IStaticGetter> NorExtWallBg1WayCurve01NoHenge => Construct(0x8cb8);
            public static FormLink<IStaticGetter> NorTowerRuinsFreeDoor01 => Construct(0x25ab3);
            public static FormLink<IStaticGetter> SMC_NorDwelling03ExtBaseANoDirt => Construct(0x31316);
            public static FormLink<IStaticGetter> SMC_EbonySwordStatic => Construct(0x3db25);
        }
    }
}
