// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class SailorMoonClub
    {
        public static class Static
        {
            private static FormLink<IStaticGetter> Construct(uint id) => new FormLink<IStaticGetter>(ModKey.MakeFormKey(id));
            public static FormLink<IStaticGetter> NorExtWallBg1WayCurve01NoHenge => Construct(0x88c);
            public static FormLink<IStaticGetter> SMC_MoonPearlStatic => Construct(0x898);
            public static FormLink<IStaticGetter> SMC_PortGateBaseStone => Construct(0x8a7);
            public static FormLink<IStaticGetter> SMC_SilverSwordStatic => Construct(0x8aa);
            public static FormLink<IStaticGetter> StockadeSupportedWoodStairs => Construct(0x8f8);
            public static FormLink<IStaticGetter> NorTowerRuinsBase => Construct(0x907);
            public static FormLink<IStaticGetter> NorTowerRuinsFreeDoor01 => Construct(0xa59);
            public static FormLink<IStaticGetter> SMC_NorDwelling03ExtBaseANoDirt => Construct(0xb35);
            public static FormLink<IStaticGetter> SMC_EbonySwordStatic => Construct(0xbb0);
        }
    }
}
