// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Skyrim;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class SailorMoonClub
    {
        public static class VisualEffect
        {
            private static FormLink<IVisualEffectGetter> Construct(uint id) => new FormLink<IVisualEffectGetter>(ModKey.MakeFormKey(id));
            public static FormLink<IVisualEffectGetter> AbsorbMoonTargetVFX01 => Construct(0x22ed);
            public static FormLink<IVisualEffectGetter> AbsorbMoonCastVFX01 => Construct(0x22ee);
        }
    }
}
