// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Skyrim;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class SailorMoonClub
    {
        public static class Weapon
        {
            private static FormLink<IWeaponGetter> Construct(uint id) => new FormLink<IWeaponGetter>(ModKey.MakeFormKey(id));
            public static FormLink<IWeaponGetter> EnchSteelBattleAxeLunar02 => Construct(0x73260);
            public static FormLink<IWeaponGetter> SMC_TriumphFork2 => Construct(0x13bb3);
            public static FormLink<IWeaponGetter> RangerShortbow => Construct(0x17735);
            public static FormLink<IWeaponGetter> EnchImperialSwordLunar01 => Construct(0x70ab2);
            public static FormLink<IWeaponGetter> EnchImperialSwordLunar02 => Construct(0x70ab3);
            public static FormLink<IWeaponGetter> EnchImperialSwordLunar03 => Construct(0x70ab4);
            public static FormLink<IWeaponGetter> EnchIronBattleaxeLunar01 => Construct(0x7325c);
            public static FormLink<IWeaponGetter> EnchIronBattleaxeLunar02 => Construct(0x7325d);
            public static FormLink<IWeaponGetter> EnchIronBattleaxeLunar03 => Construct(0x7325e);
            public static FormLink<IWeaponGetter> EnchSteelBattleAxeLunar01 => Construct(0x7325f);
            public static FormLink<IWeaponGetter> EnchSteelWarhammerLunar03 => Construct(0x7326d);
            public static FormLink<IWeaponGetter> EnchSteelBattleaxeLunar03 => Construct(0x73261);
            public static FormLink<IWeaponGetter> EnchIronGreatSwordLunar01 => Construct(0x73262);
            public static FormLink<IWeaponGetter> EnchIronGreatSwordLunar02 => Construct(0x73263);
            public static FormLink<IWeaponGetter> EnchIronGreatswordLunar03 => Construct(0x73264);
            public static FormLink<IWeaponGetter> EnchSteelGreatswordLunar01 => Construct(0x73265);
            public static FormLink<IWeaponGetter> EnchSteelGreatswordLunar02 => Construct(0x73266);
            public static FormLink<IWeaponGetter> EnchSteelGreatswordLunar03 => Construct(0x73267);
            public static FormLink<IWeaponGetter> EnchIronWarhammerLunar01 => Construct(0x73268);
            public static FormLink<IWeaponGetter> EnchIronWarhammerLunar02 => Construct(0x73269);
            public static FormLink<IWeaponGetter> EnchIronWarhammerLunar03 => Construct(0x7326a);
            public static FormLink<IWeaponGetter> EnchSteelWarhammerLunar01 => Construct(0x7326b);
            public static FormLink<IWeaponGetter> EnchSteelWarhammerLunar02 => Construct(0x7326c);
        }
    }
}
