// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class SailorMoonClub
    {
        public static class Weapon
        {
            private static FormLink<IWeaponGetter> Construct(uint id) => new FormLink<IWeaponGetter>(ModKey.MakeFormKey(id));
            public static FormLink<IWeaponGetter> SMC_TriumphFork2 => Construct(0x91d);
            public static FormLink<IWeaponGetter> RangerShortbow => Construct(0x950);
            public static FormLink<IWeaponGetter> EnchImperialSwordLunar01 => Construct(0xc41);
            public static FormLink<IWeaponGetter> EnchImperialSwordLunar02 => Construct(0xc42);
            public static FormLink<IWeaponGetter> EnchImperialSwordLunar03 => Construct(0xc43);
            public static FormLink<IWeaponGetter> EnchIronBattleaxeLunar01 => Construct(0xc51);
            public static FormLink<IWeaponGetter> EnchIronBattleaxeLunar02 => Construct(0xc52);
            public static FormLink<IWeaponGetter> EnchIronBattleaxeLunar03 => Construct(0xc53);
            public static FormLink<IWeaponGetter> EnchSteelBattleAxeLunar01 => Construct(0xc54);
            public static FormLink<IWeaponGetter> EnchSteelBattleAxeLunar02 => Construct(0xc55);
            public static FormLink<IWeaponGetter> EnchSteelBattleaxeLunar03 => Construct(0xc56);
            public static FormLink<IWeaponGetter> EnchIronGreatSwordLunar01 => Construct(0xc57);
            public static FormLink<IWeaponGetter> EnchIronGreatSwordLunar02 => Construct(0xc58);
            public static FormLink<IWeaponGetter> EnchIronGreatswordLunar03 => Construct(0xc59);
            public static FormLink<IWeaponGetter> EnchSteelGreatswordLunar01 => Construct(0xc5a);
            public static FormLink<IWeaponGetter> EnchSteelGreatswordLunar02 => Construct(0xc5b);
            public static FormLink<IWeaponGetter> EnchSteelGreatswordLunar03 => Construct(0xc5c);
            public static FormLink<IWeaponGetter> EnchIronWarhammerLunar01 => Construct(0xc5d);
            public static FormLink<IWeaponGetter> EnchIronWarhammerLunar02 => Construct(0xc5e);
            public static FormLink<IWeaponGetter> EnchIronWarhammerLunar03 => Construct(0xc5f);
            public static FormLink<IWeaponGetter> EnchSteelWarhammerLunar01 => Construct(0xc60);
            public static FormLink<IWeaponGetter> EnchSteelWarhammerLunar02 => Construct(0xc61);
            public static FormLink<IWeaponGetter> EnchSteelWarhammerLunar03 => Construct(0xc62);
        }
    }
}
